SET MODE Oracle;

CREATE SCHEMA IF NOT EXISTS LAB_BAC;

CREATE TABLE IF NOT EXISTS LAB_BAC.PEOPLE
(	ID NUMBER(20,0) NOT NULL ENABLE,
    FIRST_NAME VARCHAR2(512),
    LAST_NAME VARCHAR2(512),
    TITLE VARCHAR2(512),
    MIN_ROLE VARCHAR(32),
    CREATION_DATE TIMESTAMP
);

COMMENT ON TABLE LAB_BAC.PEOPLE IS 'Elenco di persone';
COMMENT ON COLUMN LAB_BAC.PEOPLE.id IS 'Identificativo della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.FIRST_NAME IS 'Nome della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.LAST_NAME IS 'Cognome della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.TITLE IS 'Titolo della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.CREATION_DATE IS 'Data di creazione della persona';

CREATE SEQUENCE IF NOT EXISTS LAB_BAC.SEQ_PEOPLE START WITH 10000 INCREMENT BY 1 MAXVALUE 99999999999 CACHE 1;

INSERT INTO LAB_BAC.PEOPLE VALUES ( LAB_BAC.SEQ_PEOPLE.nextval, 'Margherita', 'Hack', 'Astrofisica', null, SYSDATE );
INSERT INTO LAB_BAC.PEOPLE VALUES ( LAB_BAC.SEQ_PEOPLE.nextval, 'Alan', 'Turing', 'Matematico', null, SYSDATE );
INSERT INTO LAB_BAC.PEOPLE VALUES ( LAB_BAC.SEQ_PEOPLE.nextval, 'Richard', 'Feynman', 'Fisico', 'admin', SYSDATE );
