SET MODE Oracle;

CREATE SCHEMA IF NOT EXISTS LAB_BAC;

CREATE TABLE IF NOT EXISTS LAB_BAC.PEOPLE
(	ID NUMBER(20,0) NOT NULL ENABLE,
    UUID VARCHAR2(64) NOT NULL,
    FIRST_NAME VARCHAR2(512),
    LAST_NAME VARCHAR2(512),
    TITLE VARCHAR2(512),
    MIN_ROLE VARCHAR(32),
    CREATION_DATE TIMESTAMP
);

COMMENT ON TABLE LAB_BAC.PEOPLE IS 'Elenco di persone';
COMMENT ON COLUMN LAB_BAC.PEOPLE.id IS 'Identificativo della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.UUID IS 'ID esterno della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.FIRST_NAME IS 'Nome della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.LAST_NAME IS 'Cognome della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.TITLE IS 'Titolo della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.CREATION_DATE IS 'Data di creazione della persona';

CREATE SEQUENCE IF NOT EXISTS LAB_BAC.SEQ_PEOPLE START WITH 10000 INCREMENT BY 1 MAXVALUE 99999999999 CACHE 1;

INSERT INTO LAB_BAC.PEOPLE VALUES ( LAB_BAC.SEQ_PEOPLE.nextval, '46005e2d-4faa-4c5a-8ed2-6876d63622a7', 'Margherita', 'Hack', 'Astrofisica', null, SYSDATE );
INSERT INTO LAB_BAC.PEOPLE VALUES ( LAB_BAC.SEQ_PEOPLE.nextval, '62472b90-14a5-45b5-891e-14f9e5659680', 'Alan', 'Turing', 'Matematico', null, SYSDATE );
INSERT INTO LAB_BAC.PEOPLE VALUES ( LAB_BAC.SEQ_PEOPLE.nextval, '3ad86124-765a-4104-a2dd-e99335ff1260', 'Richard', 'Feynman', 'Fisico', 'admin', SYSDATE );
